use async_trait::async_trait;

use crate::foundation::Result;

/// Trait for extracting a typed struct from a multipart form-data request.
///
/// This trait is automatically implemented by the `#[derive(Validate)]` macro
/// for derive-based request DTOs, including text-only structs.
///
/// Text fields are extracted as strings and parsed into the target type via
/// `FromStr`. `serde_json::Value` fields are parsed from JSON strings, repeated
/// text parts populate `Vec<T>` fields in request order, and file fields are
/// streamed to a temporary file and wrapped in `UploadedFile`.
#[async_trait]
pub trait FromMultipart: Send + Sized {
    /// Extract fields from a multipart stream.
    ///
    /// The implementation iterates over all fields, matching by name, and
    /// populates the struct fields accordingly.
    async fn from_multipart(multipart: &mut axum::extract::Multipart) -> Result<Self>;

    /// Extract a value together with the raw multipart field names when available.
    ///
    /// Manual implementations remain source-compatible and default to unknown
    /// presence metadata. Implementations generated by `Validate` override this
    /// so request-level presence rules can distinguish missing and empty fields.
    async fn from_multipart_with_presence(
        multipart: &mut axum::extract::Multipart,
    ) -> Result<(Self, Option<std::collections::HashSet<String>>)> {
        Self::from_multipart(multipart)
            .await
            .map(|value| (value, None))
    }

    /// Remove temporary files owned by this multipart value.
    ///
    /// Generated implementations override this for DTOs containing
    /// `UploadedFile` fields so extractors can clean uploads when validation
    /// fails before the handler receives the value.
    async fn cleanup_multipart_files(&self) {}
}
